B_Api/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from . import views, forms, settings
from django.contrib.auth.decorators import login_required
from .forms import LoginForm

#from simulation.forms import ContactForm1, ContactForm2, ContactForm3

admin.autodiscover()



urlpatterns = [
    #url(r'^base/$', views.base, name='base'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.home, name='home'),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html', 'authentication_form': LoginForm},name='login'),
    url(r'^logout/$', auth_views.logout,{'template_name': 'login.html', 'next_page': settings.LOGIN_URL}, name='logout'),
    url(r'^component/', include('component.urls')),
    url(r'^simulation/', include('simulation.urls')),

]

component/urls.py
from django.conf.urls import url
from . import views

app_name='component'

urlpatterns = [
    url(r'^$', views.list, name='list'),
    url(r'^new/$', views.new, name='new'),
    url(r'^(?P<pk>\d+)/edit/$', views.edit, name='edit'),
    url(r'^(?P<pk>\d+)/delete/$', views.delete, name='delete'),
    url(r'^(?P<pk>\d+)/form_preview/$', views.form_preview, name='form_preview'),
]

component/models.py
import django
import jsonpickle
import simplejson as json
import six
from enum import Enum
from django.db import models
from django.utils import timezone
from B_Api.models import Publishable
from B_Api.widgets import ScriptWidget




class PythonField(models.TextField):

    def __init__(self, *args,**kwargs):
        self.model_class=self.__class__.__name__.strip('Field')
        super(PythonField,self).__init__(*args,**kwargs)
  

    def from_db_value(self, value, expression, connection, context):
        if value is None:
            return value
        try:
            # text->json
            json_obj=json.loads(value)
            # json->object
            obj=jsonpickle.decode(json_obj)
        except:
            obj=None

        return obj


    def to_python(self, value):
        if value.__class__.__name__== self.model_class:
            return value

        if value is None:
            return value

        try:
            # txt->json
            json_obj= json.loads(value) 
            # json->object
            obj=jsonpickle.decode(json_obj)
        except:
            obj=None

        return obj

    def get_prep_value(self, value):
        if not value:
            return ""
        else:
            try:
                # object->json
                json_obj=jsonpickle.encode(value)
                # json->txt
                txt=json.dumps(json_obj)
            except:
                txt=""  
            return txt

    def db_type(self, connection):
        return self.__class__.__name__.strip('from B_Api.widgets import MyAceWidgetField').lower()



class JsonField(models.TextField):

    def __init__(self, *args,**kwargs):
        #self.model_class=self.__class__.__name__.strip('Field')
        super(JsonField,self).__init__(*args,**kwargs)
  

    def from_db_value(self, value, expression, connection, context):
        if value is None:
            return value
        try:
            # text->json
            obj=json.loads(value)

        except:
            obj=None

        return obj


    def to_python(self, value):
        if is_json(value):
            return value

        if value is None:
            return value

        try:
            # txt->json
            obj= json.loads(value) 

        except:
            obj=None

        return obj

    def get_prep_value(self, value):
        if not value:
            return ""
        else:
            try:
                # json->txt
                txt=json.dumps(value)
            except:
                txt=""  
            return txt

    def db_type(self, connection):
        return self.__class__.__name__.strip('from B_Api.widgets import MyAceWidgetField').lower()


    def is_json(value):
        try:
            txt = json.loads(value)
        except ValueError:
            return False
        
        return True


class Script(object):

    def __init__(self,language="python", txt=""):
        self.language=language
        self.txt=txt



class ScriptField(PythonField):

    widget=ScriptWidget
    #widget=django.forms.TextInput
    pass


class ScriptField2(models.TextField):
    
    #widget=ScriptWidget2
    widget=django.forms.HiddenInput



class Port(object):

    def __init__(self,name="", description="", default=None):
        self.name=name
        self.description=description
        self.type=self.__class__.__name__.strip('Port')
        self.default=default

    class Meta:
        abstract=True


class StringPort(Port):

    def __init__(self,default="",*args,**kwargs):

        try:
            isinstance(default,str)
        except TypeError as err:
            print("StringPort error: %s" % format(err))

        super(StringPort,self).__init__(default=default,*args,**kwargs)


class FloatPort(Port):

    def __init__(self,default=0,*args,**kwargs):

        try:
            isinstance(default,float)
        except TypeError as err:
            print("FloatPort error: %s" % format(err))

        super(FloatPort,self).__init__(default=default,*args,**kwargs)


class PortField(PythonField):

    #widget=django.forms.TextInput
    pass


class ListField(PythonField):

    #widget=django.forms.TextInput
    pass


class Component(Publishable):
    inlet_ports=models.TextField()
    outlet_ports=models.TextField()
    function = models.TextField() 
    jacobian = models.TextField() 

              

 

component/forms.py
from django import forms
from .models import Component #, I_Port, O_Port
from B_Api.widgets import MyAceWidget, MyQuillWidget
from component.widgets import PortEditorWidget




class ComponentForm(forms.Form):

    name= forms.CharField(max_length=200) 
    description= forms.CharField(widget=MyQuillWidget)
    inlet_ports= forms.CharField(widget=PortEditorWidget)
    outlet_ports= forms.CharField(widget=PortEditorWidget) 
    function=forms.CharField(widget=MyAceWidget) 
    jacobian=forms.CharField(widget=MyAceWidget)

component/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Component
from .forms import ComponentForm
from django.contrib.auth.decorators import login_required
from django.db.models.signals import pre_save
from django.dispatch import receiver
import json
from django import forms
from form_utils.forms import BetterForm

@login_required
def list(request):
    components = Component.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'component/list.html', {'components':components})


@login_required
def new(request):
    if request.method == "POST":
        form = ComponentForm(request.POST)
        if form.is_valid():
            _name = form.cleaned_data['name']
            _description = form.cleaned_data['description']
            _author=request.user          
            _created_date = timezone.now()
            _modified_date = timezone.now()
            _published_date = timezone.now()
            _inlet_ports=form.cleaned_data['inlet_ports']
            _outlet_ports=form.cleaned_data['outlet_ports']
            _function=form.cleaned_data['function']
            _jacobian=form.cleaned_data['jacobian']

            component=Component(name=_name,
                                description=_description,
                                author=_author,
                                created_date=_created_date,
                                modified_date=_modified_date,
                                published_date=_published_date,
                                inlet_ports=_inlet_ports,
                                outlet_ports=_outlet_ports,
                                function=_function,
                                jacobian=_jacobian,
                                ) 
            component.save()
            return redirect('component:list')
    else:
        form = ComponentForm()

    return render(request, 'component/edit.html', {'form': form})

@login_required
def edit(request,pk):

    component = get_object_or_404(Component, pk=pk)

    if request.method == "POST":
        form = ComponentForm(request.POST)

        if form.is_valid():
            _name = form.cleaned_data['name']
            _description = form.cleaned_data['description']
            _author=request.user          
            _created_date = timezone.now()
            _modified_date = timezone.now()
            _published_date = timezone.now()
            _inlet_ports=form.cleaned_data['inlet_ports']
            _outlet_ports=form.cleaned_data['outlet_ports']
            _function=form.cleaned_data['function']
            _jacobian=form.cleaned_data['jacobian']

            component.name=_name
            component.description=_description
            component.author=_author
            component.created_date=_created_date
            component.modified_date=_modified_date
            component.published_date=_published_date
            component.inlet_ports=_inlet_ports
            component.outlet_ports=_outlet_ports
            component.function=_function
            component.jacobian=_jacobian
                               
            component.save()
            return redirect('component:list')

    else:
        context={'name':component.name,
                 'description':component.description,
                 'author':component.author,
                 'created_date':component.created_date,
                 'modified_date':component.modified_date,
                 'published_date':component.published_date,
                 'inlet_ports':component.inlet_ports,
                 'outlet_ports':component.outlet_ports,
                 'function':component.function,
                 'jacobian':component.jacobian,
                }
        form = ComponentForm(context)

    return render(request, 'component/edit.html', {'form': form})

@login_required
def delete(request,pk):

    component = get_object_or_404(Component, pk=pk)

    component.delete()       

    return redirect('component:list')



@login_required
def form_preview(request,pk):

    component = get_object_or_404(Component, pk=pk)

    try: 
        inlet_ports = json.loads(component.inlet_ports)
    except ValueError as error:
        raise ValueError("Error in form_preview: invalid json")
    try: 
        inlet_data = json.loads(component.inlet_data)
        print("preparing inlet_data for GET...")
        print(component.inlet_data)
    except ValueError as error:
        inlet_data={}

    InletForm=make_form(inlet_ports,prefix="inlet", values=inlet_data)
    #component.inlet_form=inlet_form({}).as_table()

    if request.method == "POST":
        inlet_form=InletForm(request.POST)
        print("Submit")
        if inlet_form.is_valid(): 
            print(inlet_form.cleaned_data)
            try: 
                component.inlet_data = json.dumps(inlet_form.cleaned_data)
                print("Saving inlet_data")
                print(component.inlet_data)
                component.save()
            except ValueError as error:
                raise ValueError("Error in form_preview: invalid json")
             

        return redirect('component:list')


    return render(request, 'component/form_preview.html', {'form': InletForm, 'ports':inlet_ports,'prefix':'inlet'})





@login_required
def form_preview_old(request,pk):

    component = get_object_or_404(Component, pk=pk)

    try: 
        inlet_ports = json.loads(component.inlet_ports)
    except ValueError as error:
        raise ParseError("Error in form_preview: invalid json")

    inlet_form=make_form(inlet_ports,prefix="inlet")
    component.inlet_form=inlet_form({}).as_table()

    if request.method == "POST":
        return redirect('component:list')

    return render(request, 'component/form_preview.html', {'form': inlet_form, 'ports':inlet_ports})


#@receiver(pre_save, sender=Component)
def form_builder(sender, instance, **kwargs):
    print("<<<<<<< form_builder >>>>>>>>>>>")

    try: 
        inlet_ports = json.loads(instance.inlet_ports)
    except ValueError as error:
        raise ParseError("Error in form_builder: invalid json")

    data=inlet_ports["data"]
    structure=inlet_ports["structure"]

    form=make_form(data, structure)
    instance.inlet_form=form({}).as_table()




def make_form(ports, prefix="", values={}):

    def make_category_field(data,values):
        name=data["name"]
        help_text=data["description"]       

    def make_string_field(data,values):
        name=data["name"]
        if name in values.keys():
            initial=values[name]
        else:
            initial=data["default"]
        help_text=data["description"]
        required=True        
        field={name:forms.CharField(initial=initial,help_text=help_text,max_length=100, label=name,required=required)}  
        return field

    def make_float_field(data,values):
        name=data["name"]
        if name in values.keys():
            initial=values[name]
        else:
            initial=data["default"]
        help_text=data["description"]
        required=True 
        field={name:forms.FloatField(initial=initial,help_text=help_text,label=name,required=required)}  
        return field


    make_field={
        "string":make_string_field,
        "float":make_float_field
    }

    fields={}


    data=ports["data"]

    for f in data:
        field_data=data[f]
        field_type=field_data["type"]

        if field_type != "category":
            field=make_field[field_type](field_data,values)
            fields.update(field)

    form=type('SimulationIOForm', (forms.BaseForm,), { 'base_fields': fields })

    # add prefix to form widgets
    form.prefix=prefix

    return form


    

component/templates/component/edit.html
{% extends 'base.html' %}

{% load staticfiles %}


{% block extra_js_files %}
       <script src="{% static 'ace_editor/js/ace.js' %}" type="text/javascript" charset="utf-8"></script>
       <script src="{% static 'quill/js/quill.min.js' %}" type="text/javascript" charset="utf-8"></script>
       <script src="{% static 'jstree/dist/jstree.min.js' %}" type="text/javascript" charset="utf-8"></script>
       <script src="{% static 'jsrender/jsrender.min.js' %}" type="text/javascript" charset="utf-8"></script>
{% endblock %} 

{% block extra_css_files %}
       <link rel="stylesheet" href="{% static 'ace_editor/css/ace_editor.css' %}">
       <link rel="stylesheet" href="{% static 'quill/css/quill.snow.css' %}">
       <link rel="stylesheet" href="{% static 'quill/css/quill_editor.css' %}">
       <link rel="stylesheet" href="{% static 'jstree/dist/themes/default/style.min.css' %}">
       <link rel="stylesheet" href="{% static 'css/component.css' %}">
{% endblock %}
 
{% block content %}
    <h1>New Component</h1>
    <form method="POST" class="form">{% csrf_token %}


    <!-- Display form errors -->
    {{ form.non_field_errors }}


    <div class="container"><div class="panel-group" id="accordion">

        <!-- 1. General panel  -->

        <div class="panel panel-default">
            <div class="panel-heading">
                <h2 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapse1">Generals</a>
                </h2>
            </div>
            <div id="collapse1" class="panel-collapse collapse in">
                <div class="panel-body">
       
                    <!-- 1.1. Input "name"-->    
                    <div class="fieldWrapper">
                        {{ form.name.errors }}
                        <label for="{{ form.name.id_for_label }}">Name:</label>
                        {{ form.name }}
                    </div>

                    <!-- 1.2 Input "description"--> 
                    <div class="fieldWrapper">
                        {{ form.description.errors }}
                        {{ form.description }}
                    </div>

                </div>
            </div>
        </div>

        <!-- 2. Inlet Ports panel -->

        <div class="panel panel-default">
            <div class="panel-heading">
                <h2 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapse2">Inlet Ports</a>
                </h2>
        </div>
            <div id="collapse2" class="panel-collapse collapse">
                <div class="panel-body">

                    <!-- 2.1 inlet port editor--> 
                        {{ form.inlet_ports.errors }}
                        {{ form.inlet_ports }}
                </div>
            </div>
        </div>

        <!-- 3. Outlet Ports panel -->

        <div class="panel panel-default">
            <div class="panel-heading">
                <h2 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapse3">Outlet Ports</a>
                </h2>
        </div>
            <div id="collapse3" class="panel-collapse collapse">
                <div class="panel-body">

                    <!-- 3.1 outlet port editor--> 
                        {{ form.outlet_ports.errors }}
                        {{ form.outlet_ports }}                   

                </div>
            </div>
        </div>
        
        <!-- 3. Function panel -->

        <div class="panel panel-default">
            <div class="panel-heading">
                <h2 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapse4">Function</a>
                </h2>
            </div>
            <div id="collapse4" class="panel-collapse collapse">
                <div class="panel-body">


                    <!-- 3.1 Input "function"--> 
                    <div class="fieldWrapper">
                        {{ form.function.errors }}
                        {{ form.function }}
                    </div>


                </div>
            </div>
        </div>

        <!-- 4. Jacobian -->

        <div class="panel panel-default">
            <div class="panel-heading">
                <h2 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collapse5">Jacobian</a>
                </h2>
            </div>
            <div id="collapse5" class="panel-collapse collapse">
                <div class="panel-body">

                    <!-- 4.1 Input "jacobian"--> 
                    <div class="fieldWrapper">                        
                        {{ form.jacobian.errors }}
                        {{form.jacobian}}
                    </div>
                </div>
            </div>
        </div>

     
    <div class="footer">       
        <button type="submit" value="save" class="save btn btn-default">Save</button>        
    </div>
    

    </form>







{% endblock %}

component/templates/component/form_preview.html
{% extends 'base.html' %}
{% load custom_filters %}
{% load staticfiles %}


{% block extra_js_files %}
       <script src="{% static 'ace_editor/js/ace.js' %}" type="text/javascript" charset="utf-8"></script>
       <script src="{% static 'quill/js/quill.min.js' %}" type="text/javascript" charset="utf-8"></script>
       <script src="{% static 'jstree/dist/jstree.min.js' %}" type="text/javascript" charset="utf-8"></script>
       <script src="{% static 'jsrender/jsrender.min.js' %}" type="text/javascript" charset="utf-8"></script>
{% endblock %} 

{% block extra_css_files %}
       <link rel="stylesheet" href="{% static 'ace_editor/css/ace_editor.css' %}">
       <link rel="stylesheet" href="{% static 'quill/css/quill.snow.css' %}">
       <link rel="stylesheet" href="{% static 'quill/css/quill_editor.css' %}">
       <link rel="stylesheet" href="{% static 'jstree/dist/themes/default/style.min.css' %}">
       <link rel="stylesheet" href="{% static 'css/component.css' %}">
       <link rel="stylesheet" href="{% static 'b_api/css/form_preview.css' %}">
{% endblock %}
 
{% block content %}
{% with children=ports|index:'structure'|index:0|index:'children' data=ports|index:'data' %}

    <div class="container"><div class="panel-group">

        <!-- 0 - Form heading -->     
        <div class='panel panel-primary'> 
            <div class='panel-heading'> 
                <h1>Inlet data</h1>
            </div> 
        </div> 


        <!-- 1 - Form body --> 
        <div class='panel-body'>
            <div id="form-preview" title="Form preview">
                <form method="POST" class="form">{% csrf_token %}

                    <!-- Display form errors -->
                    {{ form.non_field_errors }}

                    <!-- Display form -->
                    {%for child in children %} 
                        {%include "component/form_preview_fieldset.html" %}
                    {%endfor%}

                    <p><button type="submit" value="save" class="save btn btn-primary my_btn">Save</button></p>
                </form>
            </div>
        </div>
    </div>


{% endwith %}
{% endblock %}  

 

{% block extra_javascript %}

    $( function() {

        // 0 - name space
        //------------------------------------------------

        var {{prefix}}={};


        // 1 - load / save operations with hidden textarea
        //------------------------------------------------

        //{{prefix}}.DOM_to_json=function(DOM_handle){

            // get data saved in hidden field
            //var DOM_val=DOM_handle.val();

           // var json={};

            //try {
                // import data from hidden textarea
           //     json=JSON.parse(DOM_val);
           // } catch (e) {
                // for new simulation, give default values
           //     json={};
            //}

            //return json;
        //};  //DOM_to_json end



        //{{prefix}}.json_to_DOM=function(DOM_handle,json){

            //try{
                //var value=JSON.stringify(json);

                //DOM_handle.val(value);
            //} catch (e) {
                //alert('error');
                //console.error("json_to_DOM error:", e);
            //}
        //}; json_to_DOM end 


        // 2 - initialisations
        //------------------------------------------------

        {{prefix}}.init=function(){

            // 2.1 - properties

            // get handle to DOM widget storing data
            //{{prefix}}.hidden_text_DOM = $("textarea[name={{prefix}}]"); // hidden textarea to save data


            // load json data from DOM widget
            //{{prefix}}.json={{prefix}}.DOM_to_json({{prefix}}.hidden_text_DOM);



            $(".help_button").mouseenter(
                function(){ // when the mouse pointer enters the element
                    // get help text associated with this help button
                    var help_text_id=$(this).attr('data-tag');
                    var text=$("#"+help_text_id).val();
                    
                    // refresh help window content
                    help_window_editor.setText(text); 
                
                    // open help window
                    $("#help_window").show();      
                }
            );

            $(".help_button").mouseleave(
                 function(){ // when the mouse pointer leaves the element
                     // open help window
                     $("#help_window").hide();      
                 }
            );
        }; 

        // 3 - main program
        //------------------------------------------------

        {{prefix}}.init();

                 
    });  
   

{% endblock %} 

component/templates/component/form_preview_fieldset.html
{% load custom_filters %}    
    {%if child.children %}
        <fieldset>
        <legend>{{data|index:child.id|index:"name"}}</legend>

        {%for ch in child.children %}     
            {%with child=ch template_name="component/form_preview_fieldset.html" %}
                {%include template_name%}
            {%endwith%}
        {%endfor%}

        </fieldset>
    {%else%}
        <li>
            {%with field=data|index:child.id name=data|index:child.id|index:"name"  %}
                <label>{{name}}</label>
                {{form|index:name}}
                {%if field|index:"description" %}       
                    <span data-tag="id_{{name}}_help_text" class="help_button glyphicon glyphicon-question-sign"></span>
                    <textarea id="id_{{name}}_help_text" hidden> {{field|index:"description"}} </textarea>                   
                {%endif%}

            {%endwith%}
        </li>
  

    {%endif%}

component/templates/component/list.html
{% extends 'base.html' %}

{% block content %}


    <h1>Component<a href="{% url 'component:new' %}"> <span class="glyphicon glyphicon-plus"></span></a></h1>
    </br>

{% if components %}

    <table id="list" class="display" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>Name</th>
                <th>Author</th>
                <th>Created on</th>
                <th class="no-sort"></th>
            </tr>
        </thead>

        <tbody>
  {% for component in components %}
            <tr>
                <td><a href="{% url 'component:edit' component.pk %}">{{component.name}}</a></td>
                <td><a href="#">{{component.author}}</a></td>
                <td><a href="#">{{component.created_date}}</a></td>
                <td><a href="{% url 'component:delete' component.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
                    <a href="{% url 'component:form_preview' component.pk %}"><span class="glyphicon glyphicon-eye-open"></span></a></td>
            </tr>
  {% endfor %}
        </tbody>
    </table>

{% endif %}
{% endblock %}






{% block extra_javascript %}

$(document).ready(function(){
    $('#list').DataTable();
});

{% endblock %}