B_Api/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from . import views, forms, settings
from django.contrib.auth.decorators import login_required
from .forms import LoginForm

#from simulation.forms import ContactForm1, ContactForm2, ContactForm3

admin.autodiscover()



urlpatterns = [
    #url(r'^base/$', views.base, name='base'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.home, name='home'),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html', 'authentication_form': LoginForm},name='login'),
    url(r'^logout/$', auth_views.logout,{'template_name': 'login.html', 'next_page': settings.LOGIN_URL}, name='logout'),
    url(r'^component/', include('component.urls')),
    url(r'^simulation/', include('simulation.urls')),

]

simulation/urls.py
from django.conf.urls import url
from . import views


app_name='simulation'



urlpatterns = [
    url(r'^$', views.list, name='list'),
    url(r'^new/details/$', views.new_details, name='new_details'),
    url(r'^(?P<pk>\d+)/edit/details/$', views.edit_details, name='edit_details'),
    url(r'^(?P<pk>\d+)/edit/data/$', views.edit_data, name='edit_data'),
    url(r'^(?P<pk>\d+)/view_results/$', views.view_results, name='view_results'),
    url(r'^(?P<pk>\d+)/delete/$', views.delete, name='delete'),
]
 

simulation/models.py
from django.db import models
from B_Api.models import Publishable

class Simulation(Publishable):
    component=models.ForeignKey('component.Component')
    inlet_data=models.TextField()
    outlet_data=models.TextField()

              

 

simulation/forms.py
from django import forms
from B_Api.widgets import MyQuillWidget
from component.models import Component



class SimulationForm(forms.Form):

    name= forms.CharField(max_length=200, label="Name", required=True) 
    description = forms.CharField(widget=MyQuillWidget)
    component = forms.ModelChoiceField(queryset=Component.objects.all(),empty_label=None)
 
    def clean_author(self):
        return request.user

    def clean_created_date(self):
        return timezone.now()

    def clean_modified_date(self):
        return timezone.now()

    def clean_published_date(self):
        return timezone.now()

simulation/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Simulation
from .forms import  SimulationForm
from django.contrib.auth.decorators import login_required
from component.models import Component
from component.views import make_form
from django.core.urlresolvers import resolve

import json

@login_required
def list(request):
    simulations = Simulation.objects.order_by('published_date')
    return render(request, 'simulation/list.html', {'simulations':simulations})


@login_required
def new_old(request):

    components=Component.objects.all()
    inlet_ports,outlet_ports=get_ports(components)

    if request.method == "POST":
        form = SimulationForm(request.POST)
        if form.is_valid():
            cleaned_data=form.cleaned_data
            cleaned_data.update({
                'author':request.user,
                'created_date': timezone.now(),
                'modified_date': timezone.now(),
                'published_date': timezone.now()})
            simulation=Simulation(**cleaned_data) 
            simulation.save()
            return redirect('simulation:list')
    else:
        form = SimulationForm()
        templates=['simulation/edit1.html','simulation/edit2.html','simulation/edit3.html']
        steps=['About','Inlet Data','Outlet Data']
    return render(request, 'simulation/edit.html', {'form': form, 'templates':templates, 'steps':steps, 'inlet_ports':inlet_ports, 'outlet_ports':outlet_ports})



@login_required
def new_details(request):  

    if request.method == "POST":
        print("edit_details:POST")
        form = SimulationForm(request.POST)

        if form.is_valid():
            cleaned_data=form.cleaned_data
            cleaned_data.update({
                'author':request.user,
                'modified_date': timezone.now(),
                'published_date': timezone.now()})

            simulation=Simulation()

            for key in cleaned_data:
                setattr(simulation, key, cleaned_data[key])
 
            simulation.save()

            if request.POST.get("to_list"):
                return redirect("simulation:list")
            elif request.POST.get("to_edit_data"):  
                return redirect("simulation:edit_data", simulation.pk)
    else:
        form = SimulationForm()

    return render(request, 'simulation/edit_details.html', {'form': form})


@login_required
def edit_details(request,pk):  

    simulation = get_object_or_404(Simulation, pk=pk)
    components=Component.objects.all()

    if request.method == "POST":
        print("edit_details:POST")
        form = SimulationForm(request.POST)

        if form.is_valid():
            cleaned_data=form.cleaned_data
            cleaned_data.update({
                'author':request.user,
                'modified_date': timezone.now(),
                'published_date': timezone.now()})
            # if component has been changed, reset inlet/outlet data data
            if cleaned_data['component'] != simulation.component:
                simulation.inlet_data={}
                simulation.outlet_data={}

            #for key in cleaned_data:
                #setattr(simulation, key, cleaned_data[key])
            simulation.name=cleaned_data['name']
            simulation.description=cleaned_data['description']
            simulation.component=cleaned_data['component']
 
            simulation.save()

            if request.POST.get("to_list"):
                return redirect("simulation:list")
            elif request.POST.get("to_edit_data"):  
                return redirect("simulation:edit_data", simulation.pk)

    else:
        print("edit_details:GET")
        context=get_context(simulation)
        print(context)
        form = SimulationForm(context)

    return render(request, 'simulation/edit_details.html', {'form': form})



@login_required
def edit_data(request,pk):

    simulation = get_object_or_404(Simulation, pk=pk)
    component=simulation.component

    try: 
        inlet_ports = json.loads(component.inlet_ports)
    except ValueError as error:
        raise ValueError("Error in edit_data: invalid json")
    try: 
        print(simulation.inlet_data)
        inlet_data = json.loads(simulation.inlet_data)
    except ValueError as error:
        inlet_data={}
    print(inlet_ports)
    print(inlet_data)

    InletForm=make_form(inlet_ports,prefix="inlet", values=inlet_data)

    if request.method == "POST":
        inlet_form=InletForm(request.POST)
        print("Submit")
        if inlet_form.is_valid(): 
            print(inlet_form.cleaned_data)
            try: 
                simulation.inlet_data = json.dumps(inlet_form.cleaned_data)
                simulation.save()
            except ValueError as error:
                raise ValueError("Error in edit_data: invalid json")             

            if request.POST.get("to_edit_details"):
                return redirect("simulation:edit_details", simulation.pk)
            elif request.POST.get("to_view_results"): 
                simulate(pk) 
                return redirect("simulation:view_results", simulation.pk)
            elif request.POST.get("to_list"):  
                return redirect("simulation:list")
   
    return render(request, 'simulation/edit_data.html', {'form': InletForm, 'ports':inlet_ports,'prefix':'inlet'})


@login_required
def view_results(request,pk):

    simulation = get_object_or_404(Simulation, pk=pk)
    component=simulation.component

    try: 
        outlet_ports = json.loads(component.outlet_ports)
    except ValueError as error:
        raise ValueError("Error in view_results: invalid json")
    try: 
        print(simulation.outlet_data)
        outlet_data = json.loads(simulation.outlet_data)
    except ValueError as error:
        outlet_data={}
    print(outlet_ports)
    print(outlet_data)

    OutletForm=make_form(outlet_ports,prefix="outlet", values=outlet_data)

    if request.method == "POST":
        outlet_form=OutletForm(request.POST)
        print("Submit")
        if outlet_form.is_valid(): 
            #print(outlet_form.cleaned_data)
            #try: 
            #    simulation.outlet_form = json.dumps(outlet_form.cleaned_data)
            #    simulation.save()
            #except ValueError as error:
            #    raise ValueError("Error in view_results: invalid json")             

            if request.POST.get("to_edit_data"):
                return redirect("simulation:edit_data", simulation.pk)
            elif request.POST.get("to_list"):  
                return redirect("simulation:list")
   
    return render(request, 'simulation/view_results.html', {'form': OutletForm, 'ports':outlet_ports,'prefix':'outlet'})


@login_required
def delete(request,pk):

    simulation = get_object_or_404(Simulation, pk=pk)

    simulation.delete()       

    return redirect('simulation:list')


def get_context(o):
# Prepare context for edit view
    context={}
    for field in o._meta.get_fields():
        field_name=field.name
        field_type=field.get_internal_type()
        # remove Autofields
        if field_type is not 'AutoField':
            field_value=getattr(o,field_name)
            context[field_name]=field_value
    return context

def get_ports(components):
    inlet_ports={}
    outlet_ports={}
    for component in components:
        inlet_ports[component.name]=component.inlet_ports
        outlet_ports[component.name]=component.outlet_ports

    try:
        inlet_ports=json.dump(inlet_ports)
        outlet_ports=json.dump(outlet_ports)
    except TypeError:
        print("Error in 'get_ports': Unable to serialize the object")

    return (inlet_ports,outlet_ports)


def simulate(pk):
    pass

simulation/templates/simulation/contact_form.html
{% extends 'base.html' %}

{% load staticfiles %}


{% block content %}

    <p>Step {{ wizard.steps.step1 }} of {{ wizard.steps.count }}</p>
    {% for field in form %}
        {{ field.error }}
    {% endfor %}   
 
    <form action="{% url 'contact' %}" method="post">{% csrf_token %}
        <table>
            {{ wizard.management_form }}
            {% if wizard.form.forms %}
                {{ wizard.form.management_form }}
                {% for form in wizard.form.forms %}
                    {{ form }}
                {% endfor %}
            {% else %}
                {{ wizard.form }}
            {% endif %}
        </table>
        {% if wizard.steps.prev %}
            <button name="wizard_goto_step" type="submit" value="{{ wizard.steps.first }}">"first step"</button>
            <button name="wizard_goto_step" type="submit" value="{{ wizard.steps.prev }}"> "prev step"</button>
        {% endif %}
        <input type="submit" value="submit"/>
    </form>
{% endblock %}

simulation/templates/simulation/done.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block content %}

    <h2>Thank you for contacting us</h2>
    {% for form  in form_data %}
        {{ form }}
    {% endfor %}   
 
{% endblock %}

simulation/templates/simulation/edit.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load custom_filters %}

{% block extra_js_files %}
{% endblock %} 

{% block extra_css_files %}
     <link rel="stylesheet" href="{% static 'css/form-wizard.css' %}">
{% endblock %}



{% block content %}


        <!-- Top content -->

                            
                
                <div class="row">
                    <div class="col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3 form-box">
                    <div class="wizard">
                        <form method="POST" class="f1">{% csrf_token %}

                            <header class="row">
                                <div class="row errors">
                                    <!-- Display form errors -->
                                    {{ form.non_field_errors }}
                                </div>

                    		<div class="f1-steps row">
                                    {% for template in templates %}
                                        {% if forloop.first %}
                    			    <div class="f1-step active">
                                        {% else%}
                    			    <div class="f1-step inactive">
                                        {% endif%}       
                    				<div class="f1-step-icon"></div>
                    				<p>{{ steps|index:forloop.counter0 }}</p>
                    			</div>
                                    {% endfor %}
                                </div>
                            </header>
                    		
                                {% for template in templates %}
                                    <fieldset>
                                        <div class="f1-content row">
                                            {%  include template %}
                                        </div>
                                       
                                        <div class="f1-buttons row">
                                            {% if not forloop.first %}
                                                <button type="button" class="btn btn-primary btn-previous">Previous</button>
                                            {% endif%}
                                            {% if not forloop.last %}
                                                <button type="button" class="btn btn-primary btn-next ">Next</button>
                                            {% endif%}                     
                                            <button type="submit" value="save" class="btn btn-primary btn-submit">Submit</button>
                                        </div>
                                       
                                    </fieldset>
                                {% endfor %}
                    		                    	
                    	</form>
                    </div>
                </div>
                    
            </div>


<script>

jQuery(document).ready(function() {
	
    /*
        Form
    */
    $('.f1 fieldset:first').fadeIn();

  
    /*$('.f1 input[type="text"], .f1 input[type="password"], .f1 textarea').on('focus', function() {
    	$(this).removeClass('input-error');
    });*/
    
    // next step
    $('.f1 .btn-next').on('click', function() {
    	var parent_fieldset = $(this).parents('fieldset');
    	var next_step = true;
    	// navigation steps / progress steps
    	var current_active_step = $(this).parents('.f1').find('.f1-step.active');
    	
    	
    	if( next_step ) {
    		parent_fieldset.fadeOut(400, function() {
    			// change icons
    			current_active_step.removeClass('active').addClass('inactive').next().addClass('active');

    			// show next step
	    		$(this).next().fadeIn();
	    	});
    	}
    	
    });
    
    // previous step
    $('.f1 .btn-previous').on('click', function() {
    	// navigation steps / progress steps
    	var current_active_step = $(this).parents('.f1').find('.f1-step.active');
    	
    	$(this).parents('fieldset').fadeOut(400, function() {
    		// change icons
    		current_active_step.removeClass('active').addClass('inactive').prev().removeClass('inactive').addClass('active');

    		// show previous step
    		$(this).prev().fadeIn();
    	});

    });
    
    // submit
    /*$('.f1').on('submit', function(e) {
    	
    	// fields validation
    	$(this).find('input[type="text"], input[type="password"], textarea').each(function() {
    		if( $(this).val() == "" ) {
    			e.preventDefault();
    			$(this).addClass('input-error');
    		}
    		else {
    			$(this).removeClass('input-error');
    		}
    	});
    	// fields validation
    	
    });*/
    


   
});

</script>


{% endblock %}





{% block extra_javascript %}



{% endblock %} 

simulation/templates/simulation/edit_data.html
{% extends 'base.html' %}
{% load custom_filters %}
{% load staticfiles %}


{% block extra_js_files %}
       <script src="{% static 'quill/js/quill.min.js' %}" type="text/javascript" charset="utf-8"></script>
       <script src="{% static 'jsrender/jsrender.min.js' %}" type="text/javascript" charset="utf-8"></script>
{% endblock %} 

{% block extra_css_files %}
       <link rel="stylesheet" href="{% static 'quill/css/quill.snow.css' %}">
       <link rel="stylesheet" href="{% static 'quill/css/quill_editor.css' %}">
       <link rel="stylesheet" href="{% static 'b_api/css/form_preview.css' %}">
{% endblock %}
 
{% block content %}
{% with children=ports|index:'structure'|index:0|index:'children' data=ports|index:'data' %}

    <div class="container"><div class="panel-group">

        <!-- 0 - Form heading -->     
        <div class='panel panel-primary'> 
            <div class='panel-heading'> 
                <h1>Inlet data</h1>
            </div> 
        </div> 


        <!-- 1 - Form body --> 
        <div class='panel-body'>
            <div id="form-preview" title="Form preview">
                <form method="POST" class="form">{% csrf_token %}

                    <!-- Display form errors -->
                    {{ form.non_field_errors }}

                    <!-- Display form -->
                    {%for child in children %} 
                        {%include "simulation/edit_data_recursive.html" %}
                    {%endfor%}

                    <div class="btn-group" role="group" aria-label="...">
                        <button  type="submit"  name="to_edit_details" value="edit_details" class="btn btn-primary">Previous</button>
                        <button  type="submit"  name="to_view_results" value="view_results" class="btn btn-primary">Next</button>
                        <button type="submit"  name="to_list" value="list"  class="btn btn-primary">Save</button>
                    </div>
                </form>
            </div>
        </div>
    </div>


{% endwith %}
{% endblock %}  

 

{% block extra_javascript %}

    $( function() {

        // 0 - name space
        //------------------------------------------------

        var {{prefix}}={};


        // 1 - load / save operations with hidden textarea
        //------------------------------------------------

        //{{prefix}}.DOM_to_json=function(DOM_handle){

            // get data saved in hidden field
            //var DOM_val=DOM_handle.val();

           // var json={};

            //try {
                // import data from hidden textarea
           //     json=JSON.parse(DOM_val);
           // } catch (e) {
                // for new simulation, give default values
           //     json={};
            //}

            //return json;
        //};  //DOM_to_json end



        //{{prefix}}.json_to_DOM=function(DOM_handle,json){

            //try{
                //var value=JSON.stringify(json);

                //DOM_handle.val(value);
            //} catch (e) {
                //alert('error');
                //console.error("json_to_DOM error:", e);
            //}
        //}; json_to_DOM end 


        // 2 - initialisations
        //------------------------------------------------

        {{prefix}}.init=function(){

            // 2.1 - properties

            // get handle to DOM widget storing data
            //{{prefix}}.hidden_text_DOM = $("textarea[name={{prefix}}]"); // hidden textarea to save data


            // load json data from DOM widget
            //{{prefix}}.json={{prefix}}.DOM_to_json({{prefix}}.hidden_text_DOM);



            $(".help_button").mouseenter(
                function(){ // when the mouse pointer enters the element
                    // get help text associated with this help button
                    var help_text_id=$(this).attr('data-tag');
                    var text=$("#"+help_text_id).val();
                    
                    // refresh help window content
                    help_window_editor.setText(text); 
                
                    // open help window
                    $("#help_window").show();      
                }
            );

            $(".help_button").mouseleave(
                 function(){ // when the mouse pointer leaves the element
                     // open help window
                     $("#help_window").hide();      
                 }
            );
        }; 

        // 3 - main program
        //------------------------------------------------

        {{prefix}}.init();

                 
    });  
   

{% endblock %} 

simulation/templates/simulation/edit_data_recursive.html
{% load custom_filters %}    
    {%if child.children %}
        <fieldset class='edit_data_fieldset'>
        <legend>{{data|index:child.id|index:"name"}}</legend>

        {%for ch in child.children %}     
            {%with child=ch template_name="simulation/edit_data_recursive.html" %}
                {%include template_name%}
            {%endwith%}
        {%endfor%}
        </fieldset>
    {%else%}
        <li>
            {%with field=data|index:child.id name=data|index:child.id|index:"name"  type=data|index:child.id|index:"type" %}
                {%if type != 'category'  %}
                     {%if form|index:name|required  %}
                         <div class="form-group required"> 
                     {%else%}  
                         <div class="form-group "> 
                     {%endif%}                                       
                     <label class="control-label" for={{form|index:name|label}}  >{{name}}</label>
                     {{ form|index:name|add_class:"form-control"}}
                       
                   </div>
                {%endif%}
            {%endwith%}  

        </li>
  

    {%endif%}

simulation/templates/simulation/edit_details.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load custom_filters %}

{% block extra_js_files %}
     <script src="{% static 'quill/js/quill.min.js' %}" type="text/javascript" charset="utf-8"></script>
{% endblock %} 

{% block extra_css_files %}
     <link rel="stylesheet" href="{% static 'quill/css/quill.snow.css' %}">
     <link rel="stylesheet" href="{% static 'quill/css/quill_editor.css' %}">
{% endblock %}





{% block content %}

    <div class="container"><div class="panel-group">

        <!-- 0 - Form heading -->     
        <div class='panel panel-primary'> 
            <div class='panel-heading'> 
                <h1>New Simulation</h1>
            </div> 
        </div> 


        <!-- 1 - Form body --> 
        <div class='panel-body'>
 
            <form method="POST" class="form" >{% csrf_token %}


                <div class="form-error">        
                    {{ form.non_field_errors }}
                </div>

                <!-- 1.1. Input "name"-->    
                <div class="form-group required">
                    <label class="control-label" for={{ form.name.id_for_label }}>{{ form.name.label }}</label>
                    {{ form.name | add_class:"form-control"}}
                    {{ form.name.errors }}
                </div>

                <!-- 1.2. Input "description"-->    
                <div class="form-group">
                    <label class="control-label" for={{ form.description.id_for_label }}>{{ form.description.label }}</label>
                        {{ form.description | add_class:"form-control"}}
                        {{ form.description.errors }}
                </div>

                <!-- 1.3. Input "component"-->    
                <div class="form-group">
                    <label class='control-label' for={{ form.component.id_for_label}}>Component</label>
                        {{ form.component | add_class:"form-control" }}
                </div>
             

                <div class="btn-group" role="group">                       
                   <button  type="submit"  name="to_edit_data" value="edit_data" class="btn btn-primary">Next</button>
                   <button type="submit"  name="to_list" value="list"  class="btn btn-primary">Save</button>
                </div>
            
            </form>


        </div> 
    </div>

             
                                        



 {% endblock %}

simulation/templates/simulation/edit_save.html
{% extends 'base.html' %}

{% load staticfiles %}
{% load custom_filters %}


{% block extra_js_files %}
     <script src="{% static 'jquery.steps-1.1.0/jquery.steps.min.js' %}" type="text/javascript" charset="utf-8"></script>
     <script src="{% static 'quill/js/quill.min.js' %}" type="text/javascript" charset="utf-8"></script>
{% endblock %} 

{% block extra_css_files %}
     <link rel="stylesheet" href="{% static 'jquery.steps-1.1.0/jquery.steps.css' %}">
     <link rel="stylesheet" href="{% static 'quill/css/quill.snow.css' %}">
     <link rel="stylesheet" href="{% static 'quill/css/quill_editor.css' %}">
{% endblock %}
 

{% block content %}


      <form method="POST" class="form">{% csrf_token %}

      <!-- Form heading -->     
      <div class='panel panel-primary'> 
        <div class='panel-heading'> 
          <h1>New Simulation</h1>
         </div> 
      </div> 

      <!-- Display form errors -->
      {{ form.non_field_errors }}
  
      <div class='panel-body'> 

        <!-- 1.1. Input "name"-->    
        <div class="form-group">
          {{ form.name.errors }}
          <label class="control-label" for={{ form.name.id_for_label }}>{{ form.name.label }}</label>
          {{ form.name | add_class:"form-control"}}
        </div>

        <!-- 1.2. Input "desription"-->    
        <div class="form-group">
          {{ form.description.errors }}
          <label class='control-label' for={{ form.description.id_for_label}}>Description</label>
          {{ form.description | add_class:"form-control" }}
        </div>


        <!-- 1.3. Input "component"-->    
        <div class="form-group">
          <!--{{ form.component.errors }}-->
          <label class='control-label' for={{ form.component.id_for_label}}>Component</label>
          {{ form.component | add_class:"form-control" }}
        </div>


      </div>

      <button type="submit" value="save" class="save btn btn-primary my_btn">Save</button>

    </form> 
 

{% endblock %}

simulation/templates/simulation/list.html
{% extends 'base.html' %}

{% block content %}


      <!-- Form heading -->     
      <div class='panel panel-primary'> 
        <div class='panel-heading'> 
          <h1>Simulation<a href="{% url 'simulation:new_details' %}"> <span class="glyphicon glyphicon-plus white"></span></a></h1>
         </div> 
      </div> 


    


{% if simulations %}
    <div class='panel-body'> 

    <table id="list" class="display" cellspacing="0" width="100%" padding="100px">
        <thead>
            <tr>
                <th>Name</th>
                <th>Author</th>
                <th>Created on</th>
                <th>Component</th>
                <th class="no-sort"></th>
            </tr>
        </thead>

        <tbody>
  {% for simulation in simulations %}
            <tr>
                <td><a href="{% url 'simulation:edit_details' pk=simulation.pk %}">{{simulation.name}}</a></td>
                <td><a href="#">{{simulation.author}}</a></td>
                <td><a href="#">{{simulation.created_date}}</a></td>
                <td><a href="#">{{simulation.component.name}}</a></td>
                <td><a href="{% url 'simulation:delete' simulation.pk %}"><span class="glyphicon glyphicon-remove"></span></a></td>
            </tr>
  {% endfor %}
        </tbody>
    </table>

    </div>

{% endif %}
{% endblock %}






{% block extra_javascript %}

$(document).ready(function(){
    $('#list').DataTable();
});

{% endblock %}

simulation/templates/simulation/view_results_recursive.html
{% load custom_filters %}    
    {%if child.children %}
        <fieldset class='edit_data_fieldset'>
        <legend>{{data|index:child.id|index:"name"}}</legend>

        {%for ch in child.children %}     
            {%with child=ch template_name="simulation/view_results_recursive.html" %}
                {%include template_name%}
            {%endwith%}
        {%endfor%}
        </fieldset>
    {%else%}
        <li>
            {%with field=data|index:child.id name=data|index:child.id|index:"name"  type=data|index:child.id|index:"type" %}
                {%if type != 'category'  %}
                     {%if form|index:name|required  %}
                         <div class="form-group required"> 
                     {%else%}  
                         <div class="form-group "> 
                     {%endif%}                                       
                     <label class="control-label" for={{form|index:name|label}}  >{{name}}</label>
                     {{ form|index:name|add_class:"form-control"}}
                       
                   </div>
                {%endif%}
            {%endwith%}  

        </li>
  

    {%endif%}