B_Api/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from . import views, forms, settings
from django.contrib.auth.decorators import login_required
from .forms import LoginForm

#from simulation.forms import ContactForm1, ContactForm2, ContactForm3

admin.autodiscover()



urlpatterns = [
    #url(r'^base/$', views.base, name='base'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.home, name='home'),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html', 'authentication_form': LoginForm},name='login'),
    url(r'^logout/$', auth_views.logout,{'template_name': 'login.html', 'next_page': settings.LOGIN_URL}, name='logout'),
    url(r'^component/', include('component.urls')),
    url(r'^simulation/', include('simulation.urls')),

]

component/urls.py
from django.conf.urls import url
from . import views

app_name='component'

urlpatterns = [
    url(r'^$', views.list, name='list'),
    url(r'^new/$', views.new, name='new'),
    url(r'^(?P<pk>\d+)/edit/$', views.edit, name='edit'),
    url(r'^(?P<pk>\d+)/delete/$', views.delete, name='delete'),
    url(r'^(?P<pk>\d+)/form_preview/$', views.form_preview, name='form_preview'),
]

simulation/urls.py
from django.conf.urls import url
from . import views


app_name='simulation'



urlpatterns = [
    url(r'^$', views.list, name='list'),
    url(r'^new/details/$', views.new_details, name='new_details'),
    url(r'^(?P<pk>\d+)/edit/details/$', views.edit_details, name='edit_details'),
    url(r'^(?P<pk>\d+)/edit/data/$', views.edit_data, name='edit_data'),
    url(r'^(?P<pk>\d+)/view_results/$', views.view_results, name='view_results'),
    url(r'^(?P<pk>\d+)/delete/$', views.delete, name='delete'),
]
 

templates/ace_editor.html
<!--<input type="hidden" name=ace_code style="display: none;">-->
<input type="hidden" name=ace_code">
<div id="ace_editor">function foo(items) {
    var x = "All this is syntax highlighted";
    return x;
}</div>
    


<script>
    var ace_editor = ace.edit("ace_editor");
    ace_editor.setTheme("ace/theme/monokai");
    ace_editor.getSession().setMode("ace/mode/python");
    ace_editor.setOptions({
       maxLines: 15
    });

   var input = $('input[name="ace_code"]');
        editor.getSession().on("change", function () {
        input.val(editor.getSession().getValue());
    });

</script>

templates/base.html
{% load staticfiles %}



<html>
    <head>
        <title>Be APi</title>

       <!--<script src="{% static 'jquery/js/jquery-3.1.0.min.js' %}"></script>-->
       <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
       <script src="{% static 'jquery-ui-1.12.1.custom/jquery-ui.min.js' %}"></script>
       <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
       <script src="{% static 'dataTables/media/js/jquery.dataTables.min.js' %}"></script>
       {% block extra_js_files %}
       {% endblock %} 


       <link rel="stylesheet" href="{% static 'jquery-ui-1.12.1.custom/jquery-ui.min.css' %}">
       <link rel="stylesheet" href="{% static 'jquery-ui-1.12.1.custom/jquery-ui.theme.min.css' %}">
       <link rel="stylesheet" href="{% static 'jquery-ui-1.12.1.custom/jquery-ui.structure.min.css' %}">
       <!--<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
       <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-theme.min.css' %}">-->
       <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
       <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
       <link rel="stylesheet" href="{% static 'dataTables/media/css/jquery.dataTables.min.css' %}">
       <link rel="stylesheet" href="{% static 'b_api/css/b_api.css' %}">
       {% block extra_css_files %}
       {% endblock %} 
    </head>


    <body>
        <nav id="menu" class="navbar navbar-default navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>                        
                    </button>
                    <!--<a class="navbar-brand" href="{% url 'home' %}">B Api</a> -->
                </div>
             
                 <div class="collapse navbar-collapse" id="myNavbar"> 
                    <ul class="nav navbar-nav">
                        <li> <a href="{% url 'home' %}">B Api</a> </li>
                        <li> <a href="#">Projects</a> </li>
                        <li> <a href="{% url 'simulation:list' %}">Simulations</a> </li>
                        <li> <a href="{% url 'component:list' %}">Components</a> </li>
                    </ul>

		    {% if user.is_authenticated %}
                        <ul class="nav navbar-nav navbar-right">
                            <li class="dropdown">
                                <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                    <span class="glyphicon glyphicon-user"></span> {{user.username}}<span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a href="">Settings</a></li>
                                    <li role="separator" class="divider"></li>
                                    <li><a href="{% url 'logout' %}">Logout</a></li>
                                </ul>
                            </li>
                        </ul>
      					
                    {% endif %}

               </div> 	
    	    </div>
        </nav>
        <section id="main_window">
            <article class="row content container">
                {% block content %}
                {% endblock %}
            </article>
            <article class="row">
                <!--{% include "help_window.html" %}-->
            </article> 
       </section>
 

    	<div class="footer">
 
	    {% block footer %}
       	    {% endblock %}
    	</div>
   
    </body>


    <script>
        $(function(){
            $('a').each(function(){
                if ($(this).prop('href') == window.location.href) {
                    $(this).addClass('active'); $(this).parents('li').addClass('active');
                }
            });
        });
    </script>

    <script>
       {% block extra_javascript %}
       {% endblock %} 
    </script>

</html> 



 

templates/help_window.html
<div id="help_window" class="quill_editor"> 
    <div id="help_window_content"></div>
</div>

<script>
    // get handles to DOM widgets
    var help_window_editor = new Quill('#help_window_content',{ // quill editor
        modules:{
            "toolbar":true
        },
        theme: 'snow'
    }); 

    // help window is closed when the page is loaded
    $("#help_window").hide();              

</script>

templates/home.html
{% extends "base.html" %}

{% block content %}

<div class="container">
  <h2>B Api</h2>
  <div class="panel-group">
    <div class="panel panel-default">
      <div class="panel-heading">Welcome aboard</div>
      <div class="panel-body">Some news</div>
    </div>
   </div>
</div>

{% endblock %} 

templates/login.html
{% extends "base.html" %}

{% load static %}
{% block extra_css_files %}
<link rel="stylesheet" type="text/css" href="{% static 'b_api/css/login.css' %}" />
{% endblock %} 


{% block content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

<form id="loginForm" method="post" action="{% url 'login' %}">
{% csrf_token %}

  <fieldset>
    <h1> Please provide <br>
         your login credentials</h1>
    <div class="form-group">
      {{ form.username }}
    </div>
    <div class="form-group">
      {{ form.password }}
    </div>

    <button type="submit" class="btn btn-default" value="login" >Submit</button>
  
  </fieldset>


</form>

{% endblock %}